api = "0.4"

[buildpack]
id = "paketo-buildpacks/go-generate"
name = "Paketo Go Generate Buildpack"
version = "{{ .Version }}"
homepage = "https://github.com/paketo-buildpacks/go-generate"

[metadata]
include-files = ["bin/build","bin/detect", "bin/run", "buildpack.toml"]
pre-package = "./scripts/build.sh"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.paketo.stacks.tiny"
