api = "0.4"

[buildpack]
  id = "paketo-community/go-generate"
  name = "Paketo Go Generate Buildpack"
  homepage = "https://github.com/paketo-community/go-generate"

[metadata]
  include-files = ["bin/build","bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"
